POLLING_INTERVAL = 10
ENCODED_TICKET_INTERVAL = 60
RELIC_SESSION_UPDATE_INTERVAL = 200
MATCH_TYPE_LEADERBOARD_MAP = {
    0: 3,
    1: 4,
    2: 4,
    3: 4,
    4: 4,
    5: 3,
    6: 3,
    7: 4,
    8: 4,
    9: 4,
    10: 4,
    26: 13,
    27: 14,
    28: 14,
    29: 14,
    30: 14,
    18: 8,
    19: 9,
    20: 9,
    21: 9,
    22: 9
}


CIV_MAPPINGS = {
    0: {"name": "Armenians"},
    1: {"name": "Aztecs"},
    2: {"name": "Bengalis"},
    3: {"name": "Berbers"},
    4: {"name": "Bohemians"},
    5: {"name": "Britons"},
    6: {"name": "Bulgarians"},
    7: {"name": "Burgundians"},
    8: {"name": "Burmese"},
    9: {"name": "Byzantines"},
    10: {"name": "Celts"},
    11: {"name": "Chinese"},
    12: {"name": "Cumans"},
    13: {"name": "Dravidians"},
    14: {"name": "Ethiopians"},
    15: {"name": "Franks"},
    16: {"name": "Georgians"},
    17: {"name": "Goths"},
    18: {"name": "Gurjaras"},
    19: {"name": "Huns"},
    20: {"name": "Incas"},
    21: {"name": "Hindustanis"},
    22: {"name": "Italians"},
    23: {"name": "Japanese"},
    24: {"name": "Khmer"},
    25: {"name": "Koreans"},
    26: {"name": "Lithuanians"},
    27: {"name": "Magyars"},
    28: {"name": "Malay"},
    29: {"name": "Malians"},
    30: {"name": "Mayans"},
    31: {"name": "Mongols"},
    32: {"name": "Persians"},
    33: {"name": "Poles"},
    34: {"name": "Portuguese"},
    35: {"name": "Romans"},
    36: {"name": "Saracens"},
    37: {"name": "Sicilians"},
    38: {"name": "Slavs"},
    39: {"name": "Spanish"},
    40: {"name": "Tatars"},
    41: {"name": "Teutons"},
    42: {"name": "Turks"},
    43: {"name": "Vietnamese"},
    44: {"name": "Vikings"},
    45: {"name": "Achaemenids"},
    46: {"name": "Athenians"},
    47: {"name": "Spartans"},
    48: {"name": "Shu"},
    49: {"name": "Wu"},
    50: {"name": "Wei"},
    51: {"name": "Jurchens"},
    52: {"name": "Khitans"},
    55: {"name": "Macedonians"},
    56: {"name": "Thracians"},
    57: {"name": "Puru"},
    58: {"name": "Muisca"},
    59: {"name": "Mapuche"},
    60: {"name": "Tupi"},
}
